spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://configuser:configpass@localhost:8888"
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
