server:
  port: 8761

spring:
# todo: implement later
#  security:
#    user:
#      name: ${EUREKA_USERNAME:eurekaUser}
#      password: ${EUREKA_PASSWORD:eurekaPass}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
    prefer-ip-address: false
  client:
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
