server:
  port: 0

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: notification_user
    password: notification_password
